version: 2
updates:
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "daily"
    time: "04:00"
    timezone: "Europe/Berlin"
  open-pull-requests-limit: 10
  labels:
    - "dependencies"
  ignore:
    - dependency-name: "*"
      update-types: [ "version-update:semver-patch" ]

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
    time: "10:00"
    timezone: "Europe/Berlin"
  open-pull-requests-limit: 5
  labels:
    - "dependencies"
  ignore:
    - dependency-name: "*"
      update-types: [ "version-update:semver-patch" ]
